/**:
  ros__parameters:
    robot_description_kinematics:
      alpha:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.0050000000000000001
        kinematics_solver_timeout: 0.0050000000000000001
#      alpha:
#        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#        kinematics_solver_attempts: 3
#        kinematics_solver_search_resolution: 0.005
